spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sweater
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true    # структуру обслуживает Spring
  mustache:
    expose-request-attributes: true