spring:
  mail:
    host: smtp.yandex.ru
    username: temp-mail@yandex.ru
    password: cSFziPYsjEYd
    port: 465
    protocol: smtps
  datasource:
    url: jdbc:postgresql://localhost:5432/sweater
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false    # структуру обслуживает Spring
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false         # включаем во время отладки
  #  mustache:
#    expose-request-attributes: true
  freemarker:
    expose-request-attributes: true
  servlet:
    multipart:
      max-file-size: 15MB

mail:
  debug: true

upload:
  path: /D:/projects/learning/sweater/upload-files
#  path: D:\projects\learning\sweater\upload-files
app:
  mail:
    prefix: http://localhost:8080
